# docker-compose.yml
services:
  backend:
    build: ./Server
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    # depends_on removed because we are using Atlas

  frontend:
    build: ./Client
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
