# version: "3.9"

services:
  backend:
    build: ./Server
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env  # Make sure this file contains MONGODB_URL
    depends_on: []
  
  frontend:
    build: ./Client
    container_name: frontend
    restart: always
    ports:
      - "5174:80"
    depends_on:
      - backend
